import { DISPATCH_STRATEGY } from '../enum';

const APP_CONSTANT = {
  ORDER_RECEIVE_COUNT: 2,
  ORDER_RECEIVE_FREQUENCY: 1000,
  DEFAULT_DISPATCH_STRATEGY: DISPATCH_STRATEGY.FIFO,
  COURIER_ARRIVING_MIN_DELAY:3,
  COURIER_ARRIVING_MAX_DELAY:15,
};

export { APP_CONSTANT };
