import { DISPATCH_STRATEGY } from "../enum";

const APP_CONSTANT = {
  ORDER_RECEIVE_COUNT: 2,
  ORDER_RECEIVE_FREQUENCY: 1000,
  DISPATCH_STRATEGY: DISPATCH_STRATEGY.FIFO,
};

export { APP_CONSTANT };
